version: "3"
services:
  app:
    container_name: mongo_app
    restart: always
    build: .
    ports:
      - "4000:4000"
    links:
      - "mongo"
    depends_on:
      - mongo

  mongo:
    container_name: mongo    
    image: mongo        
    restart: always
    ports:
      - "27017:27017"
    # environment:
      # - MONGO_DATA_DIR=/data/db
      # - MONGO_LOG_DIR=/dev/null           
    volumes:     
      - dbdata:/data/db

  mongo-express:
    container_name: mongo-express    
    image: mongo-express        
    restart: always        
    ports:
      - 8081:8081
    depends_on:
      - mongo

volumes:
  dbdata: