version: "3.5"
services:
  app:
    container_name: elastic_app
    restart: always
    build: .
    ports:
      - "4100:4100"
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    environment:
      - eshost=http://elasticsearch:9200
    networks:
      - es-net

  elasticsearch:
    container_name: elasticsearch 
    image: elasticsearch:7.3.1
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.monitoring.collection.enabled=true   
    volumes:
      - esdata:/usr/share/elasticsearch/data:rw
    networks:
      - es-net
  
  kibana:
    image: kibana:7.3.1
    container_name: kibana
    ports:
      - '5601:5601'
    networks:
      - es-net

volumes:
  esdata:
    driver: local

networks:
  es-net:
    driver: "bridge"
    name: "es-net"
